### ISSUE TITLE
Do we want to create RecipeIngredient and ShoppingListItem classes?

### ISSUE THREAD

**Issue by laurel-thomson** [dkhwang118/CIS560_F18-Project-RecipeManager#14]
These are the "linking tables" that we have in our database schema that link Recipes with Ingredients and ShoppingLists with Ingredients.  We have C# classes for the rest of the relations in our schema - do we think that we should create classes for these two relations?

**Comment by dbramucci** [comment]
I think that adding a `IList<Ingredient>` field and creating a `List<Ingredient>` in the constructor to the `Recipe` and `ShoppingList` classes would make more sense for C# classes.
When writing C# code, it would be awkward to have to do "joins" to find out what the ingredients of a recipe are instead of doing `myRecipe.ingredients`.

**Comment by dbramucci** [comment]
Of course, because there are related quantities (the amount to use and the amount to buy respectively)
It probably makes the most sense to add a field of type `IDictionary<Ingredient, int> measuredIngredients` and if we want to see what ingredients are used we can do `measuredIngredients.Keys` and we could look up how much of ingredient is used in the dictionary.

IDictionary is defined here
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.idictionary-2?view=netframework-4.6.1

**Comment by laurel-thomson** [comment]
That sounds good to me.  So, it sounds like both the ```ShoppingList ``` and ```Recipe``` classes will use ```IDictionary<Ingredient, int> measuredIngredients```, since you will need an ingredient quantity for both a recipe and a shopping list.

**Comment by montgomerysamantha** [comment]
Yes, I like the list ideas. It makes the most sense to me but we can always add extra classes if needed.
